apiVersion: v1
kind: Pod
metadata:
  name: privileged
  namespace: bank-of-anthos
  annotations:
     configmanagement.gke.io/managed: disabled
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause
      securityContext:
        privileged: true
